name: Sync LeetCode

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 8 * * 6" # Scheduled trigger, runs every Saturday at 08:00 AM UTC

jobs:
  sync-leetcode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Sync LeetCode Submissions
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'my-folder'

# name: Sync Leetcode

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "0 8 * * 6"

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Sync
#         uses: joshcai/leetcode-sync@v1.5
#         with:
#           github-token: ${{ github.token }}
#           leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
#           leetcode-session: ${{ secrets.LEETCODE_SESSION }}
#           destination-folder: my-folder
#           verbose: true
#           commit-header: '[LeetCode Sync]'
